/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package srm_bank;

import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class Srm_closing extends javax.swing.JFrame {

    /**
     * Creates new form Srm_closing
     */
    public Srm_closing() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("banks.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BANKING SOFTWARE");
        setMaximumSize(new java.awt.Dimension(591, 450));
        setPreferredSize(new java.awt.Dimension(591, 450));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Closing Account");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 10, 270, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 80, 100, 22);
        getContentPane().add(t1);
        t1.setBounds(170, 80, 140, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Aadhar No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 120, 100, 22);

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(170, 120, 140, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reason for closing your Account :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(114, 180, 280, 30);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 350, 73, 23);

        c1.setText("You find our service slow.");
        getContentPane().add(c1);
        c1.setBounds(170, 220, 170, 23);

        c2.setText("Privacy issues.");
        getContentPane().add(c2);
        c2.setBounds(170, 250, 170, 23);

        c3.setText("Low Interest Rate.");
        getContentPane().add(c3);
        c3.setBounds(170, 280, 170, 23);

        c4.setText("Other issue");
        getContentPane().add(c4);
        c4.setBounds(170, 310, 170, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srm_bank/4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        int ac=Integer.parseInt(t1.getText());
        long ad=Long.parseLong(t3.getText());
         BankAccount obj;
            int i;
            for(i=0;i<launching_page.obje.size();i++)
            {
                obj=launching_page.obje.get(i);
                if(obj.getAcc()==ac && obj.getAadhar()==ad)
                    break;
            }
            if(i==launching_page.obje.size())
                javax.swing.JOptionPane.showMessageDialog(null, "No Account found");
             else
            {
                obj=launching_page.obje.get(i);
                String name=obj.getname();
                javax.swing.JOptionPane.showMessageDialog(null, name+" "+"Your Account Has been removed.");
                launching_page.obje.remove(i);
                t1.setText("");
                t3.setText("");
                c1.setSelected(false);
                c2.setSelected(false);
                c3.setSelected(false);
                c4.setSelected(false);// TODO add your handling code here:
    }}
catch(Exception e){
 javax.swing.JOptionPane.showMessageDialog(null, "please provide the correct input fields");}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Srm_closing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Srm_closing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Srm_closing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Srm_closing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
